name: ci-linux

on:
  push:
    branches: [ "**" ]  # all branches

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - clang
          - g++

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake libxcb1-dev libx11-dev libsdl2-dev

      - name: Configure
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
                 -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: GestaltApp-Linux-${{ matrix.compiler }}
          path: bin/Release/GestaltApp