name: ci-windows

on:
  push:
    branches: [ "**" ]  # all branches

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: >
        cmake -B build -G "Visual Studio 17 2022" -A x64
        -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: GestaltApp-Windows
        path: build/bin/Release/GestaltApp.exe