name: ci-windows

on:
  push:
    branches: [ "**" ]  # all branches

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Vulkan SDK
      run: |
        Invoke-WebRequest `
          -Uri "https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.zip" `
          -OutFile "vulkan-sdk.zip"

        Expand-Archive -Path vulkan-sdk.zip -DestinationPath "$env:GITHUB_WORKSPACE\vulkan-sdk"

    - name: Configure
      env:
        VULKAN_SDK: ${{ github.workspace }}\vulkan-sdk\VulkanSDK-1.3.275.0
        PATH: ${{ github.workspace }}\vulkan-sdk\VulkanSDK-1.3.275.0\Bin;${{ env.PATH }}
      run: >
        cmake -B build -G "Visual Studio 17 2022" -A x64
        -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: GestaltApp-Windows
        path: build/bin/Release/GestaltApp.exe