name: Build on Linux

on:
  push:
    branches: [ "**" ]  # all branches
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y ninja-build clang cmake libsdl2-dev libvulkan-dev

    # Optional: cache CPM downloads
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.cache/CPM
        key:  cpm-${{ hashFiles('**/Deps.cmake') }}

    - name: Configure
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: GestaltApp-Linux
        path: build/bin/Release/GestaltApp
